## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be use in producction.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-solr
  name: test-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-solr
  template:
    metadata:
      labels:
        app: test-solr
    spec:
      containers:
      - image: bitnami/solr
        name: solr
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-solr
  name: test-solr
spec:
  ports:
  - port: 8983
    protocol: TCP
    targetPort: 8983
  selector:
    app: test-solr
  sessionAffinity: None
  type: ClusterIP
